export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';

// PROVIDER
export const PROVIDERS_GET_ALL = 'PROVIDERS_GET_ALL';
export const PROVIDERS_GET_BY_ID = 'PROVIDERS_GET_BY_ID';
export const PROVIDERS_POST_ALL = 'PROVIDERS_POST_ALL';
export const PROVIDERS_POST_TEST = 'PROVIDERS_POST_TEST';
export const PROVIDERS_PUT_ALL = 'PROVIDERS_PUT_ALL';
export const PROVIDERS_PUT_STATUS = 'PROVIDERS_PUT_STATUS';

// CREDENTIAL
export const CREDENTIALS_GET_ALL = 'CREDENTIALS_GET_ALL';
export const CREDENTIALS_GET_BY_ID = 'CREDENTIALS_GET_BY_ID';
export const CREDENTIALS_POST_ALL = 'CREDENTIALS_POST_ALL';
export const CREDENTIALS_PUT_ALL = 'CREDENTIALS_PUT_ALL';
export const CREDENTIALS_PUT_STATUS = 'CREDENTIALS_PUT_STATUS';

// REPOSITORY
export const REPOSITORY_GET_ALL = 'REPOSITORY_GET_ALL';
export const REPOSITORY_GET_BY_ID = 'REPOSITORY_GET_BY_ID';
export const REPOSITORY_POST_ALL = 'REPOSITORY_POST_ALL';
export const REPOSITORY_PUT_ALL = 'REPOSITORY_PUT_ALL';
export const REPOSITORY_PUT_STATUS = 'REPOSITORY_PUT_STATUS';
export const REPOSITORY_GET_COUNT = 'REPOSITORY_GET_COUNT';

// PROJECT
export const PROJECTS_GET_COUNT_PROJECT = 'PROJECTS_GET_COUNT_PROJECT';
export const PROJECTS_GET_ALL = 'PROJECTS_GET_ALL';
export const PROJECTS_GET_BY_ID = 'PROJECTS_GET_BY_ID';
export const PROJECTS_POST_ALL = 'PROJECTS_POST_ALL';
export const PROJECTS_PUT_ALL = 'PROJECTS_PUT_ALL';
export const PROJECTS_PUT_STATUS = 'PROJECTS_PUT_STATUS';

// ROLE
export const ROLES_GET_ALL = 'ROLES_GET_ALL';
export const ROLES_GET_BY_ID = 'ROLES_GET_BY_ID';
export const ROLES_POST_ALL = 'ROLES_POST_ALL';
export const ROLES_PUT_ALL = 'ROLES_PUT_ALL';
export const ROLES_PUT_STATUS = 'ROLES_PUT_STATUS';

// USER
export const USERS_GET_ALL = 'USERS_GET_ALL';
export const USERS_GET_BY_ID = 'USERS_GET_BY_ID';
export const USERS_POST_ALL = 'USERS_POST_ALL';
export const USERS_PUT_ALL = 'USERS_PUT_ALL';
export const USERS_PUT_STATUS = 'USERS_PUT_STATUS';
export const USERS_PUT_FORGOT_PASSWORD = 'USERS_PUT_FORGOT_PASSWORD';
export const USERS_GET_COUNT_USER = 'USERS_GET_COUNT_USER';

// PERMISSIONS
export const PERMISSIONS_GET_ALL = 'PERMISSIONS_GET_ALL';

// SCAN HISTORY
export const SCAN_HISTORY_GET_ALL = 'SCAN_HISTORY_GET_ALL';
export const SCAN_HISTORY_GET_BY_ID = 'SCAN_HISTORY_GET_BY_ID';